attribute_means:
  elev_mean: 715.0357281553398
  slope_mean: 45.73078805825243
attribute_stds:
  elev_mean: 772.9868594812874
  slope_mean: 46.97479379837598
xarray_feature_scale:
  coords: {}
  attrs: {}
  dims: {}
  data_vars:
    APCP_surface:
      dims: []
      attrs: {}
      data: 0.8294922113418579
    DLWRF_surface:
      dims: []
      attrs: {}
      data: 149.94964599609375
    DSWRF_surface:
      dims: []
      attrs: {}
      data: 226.2925262451172
    PRES_surface:
      dims: []
      attrs: {}
      data: 35709.50390625
    QObs(mm/h):
      dims: []
      attrs: {}
      data: 0.16732385754585266
    SPFH_2maboveground:
      dims: []
      attrs: {}
      data: 0.005186231806874275
    TMP_2maboveground:
      dims: []
      attrs: {}
      data: 98.63380432128906
    UGRD_10maboveground:
      dims: []
      attrs: {}
      data: 2.5150809288024902
    VGRD_10maboveground:
      dims: []
      attrs: {}
      data: 2.7686984539031982
xarray_feature_center:
  coords: {}
  attrs: {}
  dims: {}
  data_vars:
    APCP_surface:
      dims: []
      attrs: {}
      data: 0.1423874795436859
    DLWRF_surface:
      dims: []
      attrs: {}
      data: 303.1827697753906
    DSWRF_surface:
      dims: []
      attrs: {}
      data: 188.4970245361328
    PRES_surface:
      dims: []
      attrs: {}
      data: 92957.4453125
    QObs(mm/h):
      dims: []
      attrs: {}
      data: 0.07123023271560669
    SPFH_2maboveground:
      dims: []
      attrs: {}
      data: 0.007006556261330843
    TMP_2maboveground:
      dims: []
      attrs: {}
      data: 283.87200927734375
    UGRD_10maboveground:
      dims: []
      attrs: {}
      data: 0.97260981798172
    VGRD_10maboveground:
      dims: []
      attrs: {}
      data: 0.4705375134944916
