name: bmi_lstm
channels:
  - pytorch
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - bmipy
  - bokeh
  - cpuonly
  - jupyter
  - matplotlib
  - netcdf4
  - pandas
  - python=3.10
  - pytorch
  - ruamel.yaml
  - xarray=0.16.0
  - llvm-openmp=10.0.0
