allow_subsequent_nan_losses: 1000
batch_size: 256
clip_gradient_norm: 1
clip_targets_to_zero:
- QObs(mm/h)
commit_hash: a2e9bb2
data_dir: /home/jmframe/data/CAMELS_US
dataset: hourly_camels_us
device: cuda:0
dynamic_inputs:
- APCP_surface
- TMP_2maboveground
epochs: 9
experiment_name: nh_AORC_hourly_slope_elev_precip_temp_seq999_seed101
forcings:
- aorc_hourly
head: regression
hidden_size: 126
img_log_dir: /home/jmframe/neuralhydrology/runs/nh_AORC_hourly_slope_elev_precip_temp_seq999_seed101_2801_191806/img_log
initial_forget_bias: 3
learning_rate:
  0: 0.001
  2: 0.0008
  4: 0.0005
log_interval: 5
log_n_figures: 1
log_tensorboard: false
loss: NSE
metrics:
- NSE
- KGE
model: cudalstm
num_workers: 16
number_of_basins: 515
optimizer: Adam
output_activation: linear
output_dropout: 0.4
package_version: 1.10.0
predict_last_n: 1
run_dir: ../trained_neuralhydrology_models/nh_AORC_hourly_slope_elev_precip_temp_seq999_seed101_2801_191806
save_weights_every: 1
seed: 101
seq_length: 999
static_attributes:
- elev_mean
- slope_mean
target_variables:
- QObs(mm/h)
test_basin_file: /home/jmframe/data/CAMELS_US/list_515_camels_basins_aorc.txt
test_end_date: 30/09/2023
test_start_date: 01/10/1985
train_basin_file: /home/jmframe/data/CAMELS_US/list_515_camels_basins_aorc.txt
train_dir: /home/jmframe/neuralhydrology/runs/nh_AORC_hourly_slope_elev_precip_temp_seq999_seed101_2801_191806/train_data
train_end_date: 30/09/2023
train_start_date: 01/10/2015
validate_every: 1
validate_n_random_basins: 100
validation_basin_file: /home/jmframe/data/CAMELS_US/list_515_camels_basins_aorc.txt
validation_end_date: 30/09/2004
validation_start_date: 01/10/2003
