attribute_means:
  elev_mean: 715.0357281553398
  slope_mean: 45.73078805825243
attribute_stds:
  elev_mean: 772.9868594812874
  slope_mean: 46.97479379837598
xarray_feature_scale:
  coords: {}
  attrs: {}
  dims: {}
  data_vars:
    APCP_surface:
      dims: []
      attrs: {}
      data: 0.8288211226463318
    DLWRF_surface:
      dims: []
      attrs: {}
      data: 149.99867248535156
    DSWRF_surface:
      dims: []
      attrs: {}
      data: 226.59652709960938
    PRES_surface:
      dims: []
      attrs: {}
      data: 35655.68359375
    QObs(mm/h):
      dims: []
      attrs: {}
      data: 0.16732385754585266
    SPFH_2maboveground:
      dims: []
      attrs: {}
      data: 0.005189969204366207
    TMP_2maboveground:
      dims: []
      attrs: {}
      data: 98.48518371582031
    UGRD_10maboveground:
      dims: []
      attrs: {}
      data: 2.512176513671875
    VGRD_10maboveground:
      dims: []
      attrs: {}
      data: 2.7658159732818604
xarray_feature_center:
  coords: {}
  attrs: {}
  dims: {}
  data_vars:
    APCP_surface:
      dims: []
      attrs: {}
      data: 0.14223065972328186
    DLWRF_surface:
      dims: []
      attrs: {}
      data: 303.3072814941406
    DSWRF_surface:
      dims: []
      attrs: {}
      data: 188.65264892578125
    PRES_surface:
      dims: []
      attrs: {}
      data: 92957.125
    QObs(mm/h):
      dims: []
      attrs: {}
      data: 0.07123018056154251
    SPFH_2maboveground:
      dims: []
      attrs: {}
      data: 0.007017550989985466
    TMP_2maboveground:
      dims: []
      attrs: {}
      data: 283.90106201171875
    UGRD_10maboveground:
      dims: []
      attrs: {}
      data: 0.9716606140136719
    VGRD_10maboveground:
      dims: []
      attrs: {}
      data: 0.46964654326438904
