attribute_means:
  elev_mean: 715.0357281553398
  slope_mean: 45.73078805825243
attribute_stds:
  elev_mean: 772.9868594812874
  slope_mean: 46.97479379837598
xarray_feature_scale:
  coords: {}
  attrs: {}
  dims: {}
  data_vars:
    APCP_surface:
      dims: []
      attrs: {}
      data: 0.8293927907943726
    DLWRF_surface:
      dims: []
      attrs: {}
      data: 149.94711303710938
    DSWRF_surface:
      dims: []
      attrs: {}
      data: 226.319091796875
    PRES_surface:
      dims: []
      attrs: {}
      data: 35700.71875
    QObs(mm/h):
      dims: []
      attrs: {}
      data: 0.16732385754585266
    SPFH_2maboveground:
      dims: []
      attrs: {}
      data: 0.0051871309988200665
    TMP_2maboveground:
      dims: []
      attrs: {}
      data: 98.60955047607422
    UGRD_10maboveground:
      dims: []
      attrs: {}
      data: 2.514650583267212
    VGRD_10maboveground:
      dims: []
      attrs: {}
      data: 2.768183469772339
xarray_feature_center:
  coords: {}
  attrs: {}
  dims: {}
  data_vars:
    APCP_surface:
      dims: []
      attrs: {}
      data: 0.14238004386425018
    DLWRF_surface:
      dims: []
      attrs: {}
      data: 303.2055358886719
    DSWRF_surface:
      dims: []
      attrs: {}
      data: 188.51596069335938
    PRES_surface:
      dims: []
      attrs: {}
      data: 92957.75
    QObs(mm/h):
      dims: []
      attrs: {}
      data: 0.07123037427663803
    SPFH_2maboveground:
      dims: []
      attrs: {}
      data: 0.007008550688624382
    TMP_2maboveground:
      dims: []
      attrs: {}
      data: 283.87652587890625
    UGRD_10maboveground:
      dims: []
      attrs: {}
      data: 0.9722514748573303
    VGRD_10maboveground:
      dims: []
      attrs: {}
      data: 0.47066304087638855
